fix(refactor): use csp_nonce_html_transformer library
netlify/plugin-csp-nonce pull request #96
Opened 2024-11-08 14:48 UTC by JakeChampion

[csp_nonce_html_transformer](https://github.com/JakeChampion/csp_nonce_html_transformer/) internally has a custom non-asyncify wasm build of lol-html which only includes the setAttribute method, as that is all that is needed to add nonce attributes to elements. This reduces the wasm size by ~70%. It is also using the latest v2.0.0 of lol-html.

[csp_nonce_html_transformer](https://github.com/JakeChampion/csp_nonce_html_transformer/) is a standalone library for Deno which takes in a Response instance and will add CSP directives to the configured CSP header and will add nonce attributes to the response body.

2024-11-08 21:04 UTC, ndhoule requested changes
In addition to the inline comments, a few other questions:

1. The main issue we're experiencing with the CSP extension right now is crashes at runtime; can you explain how this PR addresses that problem? Were you able to repro the problem and confirm that this changeset fixes it?
2. The CSP extension/plugin are one of our most used extensions/plugins; given how large a set of changes this is, what's our testing/rollout strategy for these changes?
3. Can you add the @netlify/composable-platform team as an admin to the https://github.com/netlify/csp_nonce_html_transformer repository?

2024-11-08 21:05 UTC, ndhoule requested changes
In addition to the inline comments, a few other questions:

1. The main issue we're experiencing with the CSP extension right now is crashes at runtime; can you explain how this PR addresses that problem? Were you able to repro the problem and confirm that this changeset fixes it?
2. The CSP extension/plugin are one of our most used extensions/plugins; given how large a set of changes this is, what's our testing/rollout strategy for these changes?
3. Can you add the @netlify/composable-platform team as an admin to the https://github.com/netlify/csp_nonce_html_transformer repository?

2024-11-08 22:06 UTC, JakeChampion commented on src/__csp-nonce.ts
> +import { csp } from "https://deno.land/x/csp_nonce_html_transformer@v2.1.0/src/index.ts";
I'm not sure how snapshot tests would work as the nonce generated is cryptographically random each time the function is executed - is that possible to exclude from the snapshot?

2024-11-08 22:09 UTC, JakeChampion commented
@ndhoule unfortunately I don't have admin rights on https://github.com/netlify/csp_nonce_html_transformer/ - I think right now only Netlify GitHub Owners are admins... @eduardoboucas I see you are an owner, would you be able to add @netlify/composable-platform team as an admin to the https://github.com/netlify/csp_nonce_html_transformer repository 🙏

2024-11-08 22:18 UTC, JakeChampion commented on manifest.yml
> +    default: true
I'm going to move this into a different PR as it is introducting new functionality and not a pure refactor like the rest

2024-11-08 22:21 UTC, ndhoule commented on src/__csp-nonce.ts
> +import { csp } from "https://deno.land/x/csp_nonce_html_transformer@v2.1.0/src/index.ts";
https://vitest.dev/guide/snapshot.html#custom-serializer

I would use a custom serializer to transform the nonces to a static value--I think it should be a pretty easy find and replace.

2024-11-08 22:42 UTC, JakeChampion commented on src/__csp-nonce.ts
> -  const querySelectors = ["script", 'link[rel="preload"][as="script"]'];
done in https://github.com/netlify/plugin-csp-nonce/pull/96/commits/1b4bc70fc586beeb9d4352a51f0b634a62f203c7

2024-11-08 22:44 UTC, JakeChampion commented on src/__csp-nonce.ts
> +import { csp } from "https://deno.land/x/csp_nonce_html_transformer@v2.1.0/src/index.ts";
Could you list some scenarios you would want to see tests for, with that list I will go ahead and implement them 👍

2024-11-08 22:49 UTC, JakeChampion commented
> In addition to the inline comments, a few other questions:
> 
>     1. The main issue we're experiencing with the CSP extension right now is crashes at runtime; can you explain how this PR addresses that problem? Were you able to repro the problem and confirm that this changeset fixes it?

Yes, the library uses a custom build of lol-html to wasm, specifically it uses a version which does not use asyncify, and asyncify was the cause of the crashes from what we could see in the logs - I've deployed this plugin to test sites which have pages of large (13MB+) html and pages of HTML which customers saw issues with, all those are behaving correctly for me, and I have given them a high load from a single POP and not seen any isolate crashes or errors thrown.

>     2. The CSP extension/plugin are one of our most used extensions/plugins; given how large a set of changes this is, what's our testing/rollout strategy for these changes?

We can release the plugin as a prerelease at first, and deploy it to some site that we own which get medium-to-large traffic, and then eventually promote it to a full release. Once at a full release, we would update the extension to use it.

2024-11-08 22:57 UTC, ndhoule commented on src/__csp-nonce.ts
> +import { csp } from "https://deno.land/x/csp_nonce_html_transformer@v2.1.0/src/index.ts";
Doing a snapshot test on `sites/index.html` is a good start. The 15MB repro would also be a good idea. You've been in this repo more than I have lately, so you would probably be in a better position to judge what things you gave special consideration to in `csp_nonce_html_transformer` that we might want to also exercise in tests here.

(You'll want to check out main, generate snapshots, and then re-run the snapshot test against your branch.)

2024-11-14 17:34 UTC, ndhoule approved these changes
Thanks for making these changes!

2024-11-15 09:48 UTC, merged